### ISSUE TITLE
LICENSE

### ISSUE THREAD

**Issue by IshitaTakeshi** [komrad36/KLERP#1]
Thank you for publishing amazing implementation. 
Do you have a specific license for this code?

**Comment by komrad36** [comment]
Hey,

Some of my bigger stuff is licensed but for the "little" things I did not bother - so, thank you very much for checking, but feel free to use as public domain. If you're feeling generous you can mention it's from me, but you don't even have to do that, really.

Hope it's useful in your application!

-Kareem
